# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'resources/ui/ogg.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(404, 416)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.labelPresentation = QtWidgets.QLabel(Dialog)
        self.labelPresentation.setWordWrap(True)
        self.labelPresentation.setObjectName("labelPresentation")
        self.verticalLayout.addWidget(self.labelPresentation)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.spinBoxOggQuality = QtWidgets.QSpinBox(self.groupBox)
        self.spinBoxOggQuality.setEnabled(False)
        self.spinBoxOggQuality.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.spinBoxOggQuality.setMinimum(0)
        self.spinBoxOggQuality.setMaximum(10)
        self.spinBoxOggQuality.setProperty("value", 7)
        self.spinBoxOggQuality.setObjectName("spinBoxOggQuality")
        self.gridLayout.addWidget(self.spinBoxOggQuality, 2, 3, 1, 1)
        self.comboBoxSamplerate = QtWidgets.QComboBox(self.groupBox)
        self.comboBoxSamplerate.setEnabled(False)
        self.comboBoxSamplerate.setObjectName("comboBoxSamplerate")
        self.gridLayout.addWidget(self.comboBoxSamplerate, 0, 3, 1, 1)
        self.labelColonSamplerate = QtWidgets.QLabel(self.groupBox)
        self.labelColonSamplerate.setObjectName("labelColonSamplerate")
        self.gridLayout.addWidget(self.labelColonSamplerate, 0, 2, 1, 1)
        self.labelColonOggQuality = QtWidgets.QLabel(self.groupBox)
        self.labelColonOggQuality.setObjectName("labelColonOggQuality")
        self.gridLayout.addWidget(self.labelColonOggQuality, 2, 2, 1, 1)
        self.checkBoxOggQuality = QtWidgets.QCheckBox(self.groupBox)
        self.checkBoxOggQuality.setObjectName("checkBoxOggQuality")
        self.gridLayout.addWidget(self.checkBoxOggQuality, 2, 0, 1, 1)
        self.checkBoxSamplerate = QtWidgets.QCheckBox(self.groupBox)
        self.checkBoxSamplerate.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.checkBoxSamplerate.setObjectName("checkBoxSamplerate")
        self.gridLayout.addWidget(self.checkBoxSamplerate, 0, 0, 1, 1)
        self.checkBoxMp3Quality = QtWidgets.QCheckBox(self.groupBox)
        self.checkBoxMp3Quality.setObjectName("checkBoxMp3Quality")
        self.gridLayout.addWidget(self.checkBoxMp3Quality, 3, 0, 1, 1)
        self.checkBoxBitDepth = QtWidgets.QCheckBox(self.groupBox)
        self.checkBoxBitDepth.setObjectName("checkBoxBitDepth")
        self.gridLayout.addWidget(self.checkBoxBitDepth, 4, 0, 1, 1)
        self.labelColonMp3Quality = QtWidgets.QLabel(self.groupBox)
        self.labelColonMp3Quality.setObjectName("labelColonMp3Quality")
        self.gridLayout.addWidget(self.labelColonMp3Quality, 3, 2, 1, 1)
        self.labelColonBitDepth = QtWidgets.QLabel(self.groupBox)
        self.labelColonBitDepth.setObjectName("labelColonBitDepth")
        self.gridLayout.addWidget(self.labelColonBitDepth, 4, 2, 1, 1)
        self.comboBoxMp3Quality = QtWidgets.QComboBox(self.groupBox)
        self.comboBoxMp3Quality.setEnabled(False)
        self.comboBoxMp3Quality.setObjectName("comboBoxMp3Quality")
        self.gridLayout.addWidget(self.comboBoxMp3Quality, 3, 3, 1, 1)
        self.comboBoxBitDepth = QtWidgets.QComboBox(self.groupBox)
        self.comboBoxBitDepth.setEnabled(False)
        self.comboBoxBitDepth.setObjectName("comboBoxBitDepth")
        self.gridLayout.addWidget(self.comboBoxBitDepth, 4, 3, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout, 0, 1, 1, 1)
        self.horizontalLayout_2.addWidget(self.groupBox)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem3)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem4)
        self.groupBoxFolder = QtWidgets.QGroupBox(Dialog)
        self.groupBoxFolder.setTitle("")
        self.groupBoxFolder.setObjectName("groupBoxFolder")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBoxFolder)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.spinBoxCopySize = QtWidgets.QSpinBox(self.groupBoxFolder)
        self.spinBoxCopySize.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.spinBoxCopySize.setAccelerated(True)
        self.spinBoxCopySize.setMaximum(10000)
        self.spinBoxCopySize.setProperty("value", 10)
        self.spinBoxCopySize.setObjectName("spinBoxCopySize")
        self.gridLayout_2.addWidget(self.spinBoxCopySize, 2, 1, 1, 1)
        self.checkBoxVideo = QtWidgets.QCheckBox(self.groupBoxFolder)
        self.checkBoxVideo.setObjectName("checkBoxVideo")
        self.gridLayout_2.addWidget(self.checkBoxVideo, 0, 0, 1, 2)
        self.checkBoxAudio = QtWidgets.QCheckBox(self.groupBoxFolder)
        self.checkBoxAudio.setChecked(True)
        self.checkBoxAudio.setObjectName("checkBoxAudio")
        self.gridLayout_2.addWidget(self.checkBoxAudio, 1, 0, 1, 2)
        self.label_4 = QtWidgets.QLabel(self.groupBoxFolder)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 2, 0, 1, 1)
        self.horizontalLayout_3.addWidget(self.groupBoxFolder)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem5)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem6)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.toolButtonOutputPath = QtWidgets.QToolButton(Dialog)
        icon = QtGui.QIcon.fromTheme("folder-open")
        self.toolButtonOutputPath.setIcon(icon)
        self.toolButtonOutputPath.setObjectName("toolButtonOutputPath")
        self.horizontalLayout.addWidget(self.toolButtonOutputPath)
        self.labelOutputPath = QtWidgets.QLabel(Dialog)
        self.labelOutputPath.setObjectName("labelOutputPath")
        self.horizontalLayout.addWidget(self.labelOutputPath)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Convert to OGG"))
        self.labelPresentation.setText(_translate("Dialog", "Convert file to OGG."))
        self.comboBoxSamplerate.setToolTip(_translate("Dialog", "<html><head/><body><p>44.100 KHz is used for Audio CD.<br/>48.000 KHz is commonly used for video.</p><p>Audio quality and file size increases with the value.</p></body></html>"))
        self.labelColonSamplerate.setText(_translate("Dialog", ":"))
        self.labelColonOggQuality.setText(_translate("Dialog", ":"))
        self.checkBoxOggQuality.setText(_translate("Dialog", "Change quality to"))
        self.checkBoxSamplerate.setToolTip(_translate("Dialog", "<html><head/><body><p>Check it if you want to specify the samplerate of the converted file(s).</p><p>If you don\'t check it, converted files will have the same samplerate as input files.</p></body></html>"))
        self.checkBoxSamplerate.setText(_translate("Dialog", "Change samplerate to"))
        self.checkBoxMp3Quality.setText(_translate("Dialog", "Change quality to "))
        self.checkBoxBitDepth.setText(_translate("Dialog", "Change bit depth to"))
        self.labelColonMp3Quality.setText(_translate("Dialog", ":"))
        self.labelColonBitDepth.setText(_translate("Dialog", ":"))
        self.spinBoxCopySize.setSuffix(_translate("Dialog", "Mb"))
        self.checkBoxVideo.setText(_translate("Dialog", "Extract audio tracks from video files"))
        self.checkBoxAudio.setText(_translate("Dialog", "Convert audio files"))
        self.label_4.setText(_translate("Dialog", "Copy other files until :"))
        self.toolButtonOutputPath.setText(_translate("Dialog", "..."))
        self.labelOutputPath.setText(_translate("Dialog", "<html><head/><body><p>Output folder:<br/><span style=\" font-style:italic;\">~/Music/Didier Barbelavie/</span></p></body></html>"))

